<?php

$this->language		    = array("change" => "изменить",
				    "changed" => "изменено",
				    "comment" => "о(б)судить",
				    "text" => "текст",
				    "header" => "заголовок",
				    "controls" => "управление",
				    "lang" => "язык",
				    "auth" => "авторизация",
				    "delete" => "удалить",
				    "undelete" => "восстановить",
				    "add" => "добавить",
				    "decrypt" => "расшифровать",
				    "pgpkey" => "pgp-ключик",
				    "aboutme" => "о голове",
				    "aboutengine" => "о сердце",
				    "archive" => "архив",
				    "keys" => "ключи",
				    "actions" => "действия",
				    "allkeys" => "все ключи",
				    "allbookmarks" => "все закладки",
				    "allcomments" => "все дебаты",
				    "key" => "ключ",
				    "theme" => "тема",
				    "style" => "стиль",
				    "advert" => "реклама",
				    "keysubj" => "ключевая тема",
				    "keysubjs" => "ключевые темы",
				    "last" => "последние",
				    "inforum" => "в форуме",
				    "all" => "все",
				    "more" => "читать дальше",
				    "at" => "в",
				    "name" => "имя",
				    "email" => "е-Mail",
				    "subject" => "тема",
				    "subjects" => "темы",
				    "password" => "пароль",
				    "category" => "категория",
				    "categories" => "категории",
				    "description" => "описание",
				    "url" => "url",
				    "file" => "файл",
				    "submit" => "[отправить]",
				    "savecont" => "[сохранить и продолжать]",
				    "login" => "регистрация/войти",
				    "logout" => "выйти",
				    "addons" => "дополнительно",
				    "bookmarks" => "закладки",
				    "xmlfeeds" => "XML-лента",
				    "tobookmarks" => "заложить",
				    "comments" => "дебаты и споры",
				    "calendar" => "календарь",
				    "links" => "рекомендую",
				    "banners" => "костяшки",
				    "link" => "ссылка",
				    "seealso" => "см. также",
				    "cite" => "цитировать",
				    "download" => "скачать",
				    "subscribe" => "Получать по почте уведомления о добавлении комментариев",
				    "email2author" => "написать e-mail автору",
				    "author" => "Автор",
				    "count" => "количество", 
				    "sure" => "Вы уверены?",
				    "postedby" => "автор: ",
				    "search" => "поиск",
				    "searchdesc" => "поиск по вхождению в тексте, теме и ключевых словах",
				    "public" => "общие",
				    "friends" => "соратники",
				    "readme" => "прочти это", 
				    "permanent" => "избранное",
				    "hidden" => "скрыто",
				    "remark" => "ремарка",
				    "menu" => "меню",
				    "security" => "безопасность",
				    "deleted" => "удаленное");

$this->language['site_modules'] = array("blog" => "мысли и события",
			            "comments" => "дебаты и споры",
			            "admin" => "администрирование",
			            "external" => "внешняя ссылка",
			            "gizmo" => "узелки и записки",
			            "local" => "локальная ссылка",
			            "public" => "общая",
			            "about" => "голова и сердце");

$this->language['site_actions'] = array("show" => "просмотр",
				    "change" => "изменение",
				    "edit" => "редактирование",
				    "add" => "добавление",
				    "delete" => "удаление",
				    "subjects" => "темы",
				    "bookmarks" => "закладки",
				    "keys" => "ключи",
				    "all" => "все",
				    "last" => "последние",
				    "archive" => "архив",
				    "search" => "поиск");

$this->language['errors']	    = array ("noname" => "Вы не указали имя!<br />",
				    "notext" => "Вы не ввели текст!<br />",
				    "nosubj" => "Вы не указали тему!<br />",
				    "nofile" => "Вы не указали имя файла!<br />",
				    "noimage" => "Это не изображение!<br />",
				    "nocode" => "Вы ввели неверный код!<br />",
				    "nocopу" => "Не могу скопировать файл %s в %s/%s!<br />",
				    "nosize" => "Размер файла больше %s байт!<br />",
				    "noemail" => "Вы не указали e-mail или ошиблись при вводе!<br />");			

?>
