            <tr id="text01">
    	     <td width="10%" align="right" valign="top">&nbsp;</td>
	     <td width="90%" align="left" colspan="3" align="center"><nobr><a href="javascript:addTag('**', '**')" title="[полужирный шрифт]"><img src="images/edit/icon-bold.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag('//', '//')" title="[наклонный шрифт]"><img src="images/edit/icon-italic.png" class="actions" /></a>&nbsp;&nbsp; <a href="javascript:addTag('__', '__')" title="[подчеркнутый шрифт]"><img src="images/edit/icon-under.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag('--', '--')" title="[зачеркнутый шрифт]"><img src="images/edit/icon-strike.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag('vv', 'vv')" title="[под-текст]"><img src="images/edit/icon-sub.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag('^^', '^^')" title="[над-текст]"><img src="images/edit/icon-super.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag('<<', '<<')" title="[по левому краю]"><img src="images/edit/icon-left.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag('>>', '<<')" title="[по центру]"><img src="images/edit/icon-center.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag('>>', '>>')" title="[по правому краю]"><img src="images/edit/icon-right.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:createLink()" title="[ссылка с описанием]"><img src="images/edit/icon-url.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag('<[', ']>')" title="[цитата]"><img src="images/edit/icon-quote.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag(' ', ' **[date]**')" title="[текущая дата]"><img src="images/edit/icon-date.png" class="actions" /></a>&nbsp;&nbsp;<a href="javascript:addTag(' ', ' **[time]**')" title="[текущее время]"><img src="images/edit/icon-time.png" class="actions" /></a></nobr>
	     <div style=" float : right; position : static; margin-top : -25px; margin-right : 30px; "><a onClick="hideIt('post_titles');" style=" cursor: pointer; " title="[ссылка с предидущие посты]"><img src="images/edit/icon-posts.png" class="actions" /></a></div><div id="post_titles" style="display : none; float : right; position : absolute; left : 60%; width : 30%; height : 30%; overflow : visible; background : #DDDDDD; color : #333333; border : 3px double #000000; line-height : 10px; "><select style="width : 100%; height : 100%; " value="" multiple onDblClick="addTag('[post:', ':'+this.value+']'); hideIt('post_titles'); "><?= $session->utils->getPostsList(true); ?></select></div>
	     <? if ($session->module == "gizmo"): ?>
	       <div style=" float : right; position : static; margin-top : -25px; margin-right : 60px; "><a onClick="hideIt('keys_titles');" style=" cursor: pointer; " title="[ссылка на ключи]"><img src="images/edit/icon-posts.png" class="actions" /></a></div><div id="keys_titles" style="display : none; float : right; position : absolute; left : 60%; width : 30%; height : 30%; overflow : visible; background : #DDDDDD; color : #333333; border : 3px double #000000; line-height : 10px; "><select style="width : 100%; height : 100%; " value="" multiple onDblClick="addTag('[key:', ':'+this.value+']'); hideIt('keys_titles'); "><?= $session->utils->getKeysList($session->module, true, true); ?></select></div>
	     <? endif; ?>
	     <div style=" float : right; position : static; margin-top : -25px; "><a href="http://wiki.inses.ru/InTerra/using/manual/content/wiki/" target="_blank" title="[помощь по wackowiki]"><img src="images/edit/icon-help.png" class="actions" /></a></div>
	     </td>
	    </tr>