<?php

$this->language			    = array("change" => "change",
				    "changed" => "changed",
				    "comment" => "comment",
				    "text" => "text",
				    "header" => "header",
				    "controls" => "controls",
				    "lang" => "language",
				    "auth" => "authorization",
				    "delete" => "delete",
				    "undelete" => "undelete",
				    "add" => "add",
				    "decrypt" => "decrypt",
				    "pgpkey" => "pgp-key",
				    "aboutme" => "about me",
				    "aboutengine" => "about site engine",
				    "archive" => "archive",
				    "keys" => "keys",
				    "actions" => "actions",
				    "allkeys" => "all keys",
				    "allbookmarks" => "all bookmarks",
				    "allcomments" => "all comments",
				    "key" => "key",
				    "theme" => "theme",
				    "style" => "style",
				    "advert" => "advertisement",
				    "keysubj" => "key subject",
				    "keysubjs" => "keys subjects",
				    "last" => "last",
				    "inforum" => "in forum",
				    "all" => "all",
				    "more" => "read more",
				    "at" => "at",
				    "name" => "name",
				    "email" => "e-Mail",
				    "subject" => "subject",
				    "subjects" => "subjects",
				    "password" => "password",
				    "category" => "category",
				    "description" => "description",
				    "url" => "url",
				    "file" => "file",
				    "submit" => "[send]",
				    "savecont" => "[save & contunue]",
				    "login" => "[register]/[login]",
				    "logout" => "[logout]",
				    "addons" => "add-ons",
				    "bookmarks" => "bookmarks",
				    "xmlfeeds" => "XML-feeds",
				    "tobookmarks" => "bookmark it",
				    "calendar" => "calendar",
				    "comments" => "comments",
				    "links" => "links",
				    "banners" => "banners",
				    "link" => "link",
				    "seealso" => "see also",
				    "cite" => "citate",
				    "download" => "download",
				    "subscribe" => "Receive notifies about any changes by e-mail",
				    "email2author" => "write e-mail to author",
				    "author" => "Author",
				    "count" => "count",
				    "sure" => "Are you sure?",
				    "search" => "search",
				    "postedby" => "posted by",
				    "searchdesc" => "search for entry in text, subject and keyword list",
				    "public" => "public",
				    "friends" => "friends",
				    "hidden" => "hidden",
				    "remark" => "remark",
				    "menu" => "menu",
				    "security" => "security",
				    "deleted" => "deleted");

$this->language['site_modules']     = array("blog" => "blog",
				    "comments" => "comments",
				    "admin" => "administrations",
				    "external" => "external",
				    "gizmo" => "gizmo",
				    "local" => "local",
				    "public" => "public",
			            "about" => "about...");
																									    
$this->language['site_actions']	    = array("show" => "show",
				    "change" => "change",
				    "edit" => "edit",
				    "add" => "add",
				    "delete" => "delete",
				    "subjects" => "subjects",
				    "bookmarks" => "bookmarks",
				    "keys" => "keys",
				    "all" => "all",
				    "archive" => "archive",
				    "search" => "search");

$this->language['errors']           = array ("noname" => "No name given!<br />",
                                    "notext" => "No text given!<br />",
		                    "nosubj" => "No subject given!<br />",
		                    "nofile" => "No filename given!<br />",
       				    "nocode" => "Invalid key code!<br />",
		                    "noimage" => "This is no image/picture file!<br />",
		                    "nocopу" => "Cannot copy file %s to %s/%s!<br />",
		                    "nosize" => "Filesize limit excess - %s bytes limit!<br />",
                                    "noemail" => "No e-mail given or invalid!<br />");

?>
