<!-- $Id: a_copyleft.php,v 1.4 2005/04/26 07:09:27 hunter Exp $ -->
  <tr>
    <td width="100%" height="100%" align="center" valign="middle" colspan="3">
      <br /><nobr><a href="http://www.debian.org/" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>><img src="images/debian-mini.png" border="0" title="powered by Debian GNU/Linux" /></a>&nbsp;<a href="http://www.catb.org/hacker-emblem/" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>><img src="http://www.catb.org/hacker-emblem/hacker.png" border="0" title="hacker emblem" /></a>&nbsp;<a href="http://www.npj.ru/hunter/" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>><img src="images/npj-user.png" border="0" title="NPJ user" /></a>&nbsp;<a href="http://npj.ru/foreign/rss/ego/" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>><img src="images/npj-syndicated.png" border="0" title="syndicated by NPJ" /></a>&nbsp;<? if ($config->ngine_validities['css20']): ?><a href="http://jigsaw.w3.org/css-validator/validator/referer" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>><img src="images/css-valid.png" border="0" title="CSS 2.0 Valid" /></a>&nbsp;<? endif; ?><? if ($config->ngine_validities['xhtml4x']): ?><a href="http://validator.w3.org/check/referer" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>><img src="images/xhtml-valid.png" border="0" title="xHTML 4.x Valid" /></a>&nbsp;<? endif; ?>
<? if (($config->export_to_rss) && (in_array($session->module, $config->export_in_modules))): ?><? if ($config->ngine_validities['rss20']): ?><a href="http://feedvalidator.org/check.cgi?url=<?= $config->site_url.$session->utils->makeHRURL($session->module."&action=rss20"); ?>" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>><img src="images/rss-valid.png" border="0" title="RSS 2.0 Valid" /></a>&nbsp;<? endif; ?><a href="<?= $session->utils->makeHRURL($session->module."&action=rss20"); ?>"><img src="images/rss2.gif" border="0" title="RSS 2.0 feed" /></a>&nbsp;<? endif; ?>
<? if (($config->export_to_atom) && (in_array($session->module, $config->export_in_modules))): ?><? if ($config->ngine_validities['atom03']): ?><a href="http://feedvalidator.org/check.cgi?url=<?= $config->site_url.$session->utils->makeHRURL($session->module."&action=atom03"); ?>" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>><img src="images/atom-valid.png" border="0" title="ATOM 0.3 Valid" /></a>&nbsp;<? endif; ?><a href="<?= $session->utils->makeHRURL($session->module."&action=atom03"); ?>"><img src="images/atom-03.png" border="0" title="ATOM 0.3 feed" /></a>&nbsp;<? endif; ?></nobr><br />
      <?= $session->utils->setCounter(); ?>
      <br /><hr /><span class="hits"><nobr>Powered by <a href="<?= $session->utils->makeHRURL($config->ngine_url); ?>"><?= $config->ngine_name."  v".$config->ngine_version; ?></a>. &copy;opyLeft &amp; &copy;odeRight by <a href="mailto:<?= $session->utils->hideEMail($config->ngine_author_email); ?>"><?= $config->ngine_author; ?></a> (icq#<a href="http://web.icq.com/wwp/1,,,00.html?Uin=5005747" target="_blank"><?= $config->ngine_author_uin; ?></a>). No Rights Reserved.</nobr></span><br />
      <span class="hits">Except where noted otherwise, <strong>all content</strong> on this site is licensed under a <a href="http://creativecommons.org/licenses/by/2.0/" target="_bank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>>Creative Commons license</a>.</span><br />
    <? if ($config->use_wackoformatter): ?>
        <span class="hits">Additionaly powered by <a href="http://wackowiki.com/projects/wackoformatter" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>>WackoFormatter</a>. Copyright &copy; by <a href="http://wackowiki.com/team" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>>WackoWiki team</a>. All rights reserved.</span><br />
    <? endif; ?>
    <?  if ($config->use_typografica): ?>
        <span class="hits">Additionaly powered by <a href="http://www.pixel-apes.com/typografica" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>>typografica</a>. Copyright &copy; by <a href="http://www.pixel-apes.com/" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>>Pixel-Apes</a>. All rights reserved.</span><br />
    <? endif; ?>
    <span class="hits"><strong><?= $config->ngine_name; ?></strong> released without warranty under the terms of the <a href="http://www.opensource.org/licenses/artistic-license.php" target="_blank" <?= ($config->use_google_nofollow?"rel=\"nofollow\"":""); ?>>Artistic License</a>.</span>
    </td>
  </tr>
<!-- eof $Id: a_copyleft.php,v 1.4 2005/04/26 07:09:27 hunter Exp $ -->
